# Dynamic graph creation and manipulation
# The 3D structure of the graph is generated by processing its nodes using a Turtle procedural geometry approach

module L
    using VirtualPlantLab
    struct N <: Node
        val::Int
    end
end

import .L
import GLMakie
using VirtualPlantLab
PlantGraphs.reset_id!()
axiom=L.N(1)+(L.N(3)+L.N(4)) +L.N(2) + (L.N(5)+L.N(6))
draw(axiom)
data(axiom[2])

graph = Graph(axiom = axiom)
data(graph[2])